language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rake spec"
notifications:
  email:
    - ryan@spreecommerce.com
    - jdyer@spreecommerce.com
    - brian@spreecommerce.com
